# ============================================================
# CIM Tag assignments for Anthropic TA
# ============================================================

# Application State data model tags
[eventtype=anthropic_application_state]
application = enabled
state = enabled

[eventtype=anthropic_completion_usage]
application = enabled
state = enabled

[eventtype=anthropic_claude_code_usage]
application = enabled
state = enabled
