# ============================================================
# CIM Tag assignments for OpenAI TA
# ============================================================

# Authentication data model tags
[eventtype=openai_authentication]
authentication = enabled

[eventtype=openai_authentication_login]
authentication = enabled

[eventtype=openai_account_management]
authentication = enabled
change = enabled

# Application State data model tags
[eventtype=openai_application_state]
application = enabled
state = enabled

[eventtype=openai_completion_usage]
application = enabled
state = enabled
